export default {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',

  LOAD_ME_REQUEST: 'LOAD_ME_REQUEST',
  LOAD_ME_SUCCESS: 'LOAD_ME_SUCCESS',
  LOAD_ME_FAILURE: 'LOAD_ME_FAILURE',
}
