// actions for authentication
export const USER__SIGN_UP = 'USER__SIGN_UP'
export const USER__SIGN_UP_SUCCESS = 'USER__SIGN_UP_SUCCESS'
export const USER__SIGN_UP_FAILURE = 'USER__SIGN_UP_FAILURE'
export const USER__LOGIN = 'USER__LOGIN'
export const USER__LOGIN_SUCCESS = 'USER__LOGIN_SUCCESS'
export const USER__LOGIN_FAILURE = 'USER__LOGIN_FAILURE'
export const USER__LOGOUT = 'USER__LOGOUT'

export const SIGN_UP = 'SIGN_UP'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE'
export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOG_OUT = 'LOG_OUT'

export const LOAD_ME = 'LOAD_ME'
export const LOAD_ME_SUCCESS = 'LOAD_ME_SUCCESS'
export const LOAD_ME_FAILURE = 'LOAD_ME_FAILURE'

// action for sitemap
export const STREAMING_INIT_WEBSOCKET = 'STREAMING_INIT_WEBSOCKET'
export const STREAMING_CLOSE_WEBSOCKET = 'STREAMING_CLOSE_WEBSOCKET'
export const GET_STREAMING_URL = 'GET_STREAMING_URL'
export const FETCH_CAM_STREAMING_URL = 'FETCH_CAM_STREAMING_URL'
export const GET_STREAMING_URL_SUCCESS = 'GET_STREAMING_URL_SUCCESS'
export const FETCH_CAM_STREAMING_URL_SUCCESS = 'FETCH_CAM_STREAMING_URL_SUCCESS'
export const FETCH_CAM_STREAMING_URL_FAILURE = 'FETCH_CAM_STREAMING_URL_FAILURE'
export const CLOSE_PREV_STREAMING = 'CLOSE_PREV_STREAMING'

//action for camera
// export const ACTIVE_ADD_CAMERA = 'ACTIVE_ADD_CAMERA'
// export const DISABLE_ADD_CAMERA = 'DISABLE_ADD_CAMERA'
export const GOTO_SITEMAP_PAGE = 'GOTO_SITEMAP_PAGE'
export const EXIT_SITEMAP_PAGE = 'EXIT_SITEMAP_PAGE'
export const CHANGE_CAMERA_PARAMS = 'CHANGE_CAMERA_PARAMS'
export const GET_CAMERAS = 'GET_CAMERAS'
export const GET_CAMERAS_SUCCESS = 'GET_CAMERAS_SUCCESS'
export const GET_CAMERAS_FAILURE = 'GET_CAMERAS_FAILURE'
export const GET_CAMERA = 'GET_CAMERA'
export const GET_CAMERA_SUCCESS = 'GET_CAMERA_SUCCESS'
export const GET_CAMERA_FAILURE = 'GET_CAMERA_FAILURE'
export const ADD_CAMERA = 'ADD_CAMERA'
export const ADD_CAMERA_SUCCESS = 'ADD_CAMERA_SUCCESS'
export const ADD_CAMERA_FAILURE = 'ADD_CAMERA_FAILURE'
export const EDIT_CAMERA = 'EDIT_CAMERA'
export const EDIT_CAMERA_SUCCESS = 'EDIT_CAMERA_SUCCESS'
export const EDIT_CAMERA_FAILURE = 'EDIT_CAMERA_FAILURE'
export const DELETE_CAM = 'DELETE_CAM'
export const DELETE_CAM_SUCCESS = 'DELETE_CAM_SUCCESS'
export const DELETE_CAM_FAILURE = 'DELETE_CAM_FAILURE'
export const CLEAR_CAMERA_ERRORS = 'CLEAR_CAMERA_ERRORS'

//snapshot
export const GET_CAM_SNAPSHOT = 'GET_CAM_SNAPSHOT'
export const FETCH_CAM_SNAPSHOT = 'FETCH_CAM_SNAPSHOT'
export const GET_CAM_SNAPSHOT_SUCCESS = 'GET_CAM_SNAPSHOT_SUCCESS'
export const FETCH_CAM_SNAPSHOT_SUCCESS = 'FETCH_CAM_SNAPSHOT_SUCCESS'
export const FETCH_CAM_SNAPSHOT_FAILURE = 'FETCH_CAM_SNAPSHOT_FAILURE'

//action for cam
export const FETCH_ALL_CAMS = 'FETCH_ALL_CAMS'
export const FETCH_ALL_CAMS_SUCCESS = 'FETCH_ALL_CAMS_SUCCESS'
export const FETCH_ALL_CAMS_FAILURE = 'FETCH_ALL_CAMS_FAILURE'
// connect to camera
export const CONNECT_TO_CAM = 'CONNECT_TO_CAM'
export const CONNECT_TO_CAM_SUCCESS = 'CONNECT_TO_CAM_SUCCESS'
export const CONNECT_TO_CAM_FAILURE = 'CONNECT_TO_CAM_FAILURE'
//config camera's params
export const CONFIG_CAM_PARAMS = 'CONFIG_CAM_PARAMS'
export const CONFIG_CAM_PARAMS_SUCCESS = 'CONFIG_CAM_PARAMS_SUCCESS'
export const CONFIG_CAM_PARAMS_FAILURE = 'CONFIG_CAM_PARAMS_FAILURE'
//config camera's functions
export const CONFIG_CAM_FUNCTIONS = 'CONFIG_CAM_FUNCTIONS'
export const CONFIG_CAM_FUNCTIONS_SUCCESS = 'CONFIG_CAM_FUNCTIONS_SUCCESS'
export const CONFIG_CAM_FUNCTIONS_FAILURE = 'CONFIG_CAM_FUNCTIONS_FAILURE'

export const GET_DATA_BEFORE_SEARCH = 'GET_DATA_BEFORE_SEARCH'

// get cam configs
export const CONFIG_CAM = 'CONFIG_CAM'

// get cam location via GoogleMapApi
export const GET_CAMERA_LOCATION = 'GET_CAMERA_LOCATION'
export const FETCH_CAM_LOCATION = 'FETCH_CAM_LOCATION'
export const FETCH_CAM_LOCATION_SUCCESS = 'FETCH_CAM_LOCATION_SUCCESS'
export const FETCH_CAM_LOCATION_FAILURE = 'FETCH_CAM_LOCATION_FAILURE'

export const CHANGE_CAM_LOCATION = 'CHANGE_CAM_LOCATION'
export const CHANGE_CAM_LOCATION_SUCCESS = 'CHANGE_CAM_LOCATION_SUCCESS'
export const CHANGE_CAM_LOCATION_FAILURE = 'CHANGE_CAM_LOCATION_FAILURE'

//change cam connection
export const CHANGE_CAM_CONNECTION_PARAMS = 'CHANGE_CAM_CONNECTION_PARAMS'
export const CHANGE_CAM_POLITICAL = 'CHANGE_CAM_POLITICAL'
export const CHANGE_CURRENT_CAM_COOR = 'CHANGE_CURRENT_CAM_COOR'

// fetch/edit camera's connection
export const GET_CAM_CONNECTION = 'GET_CAM_CONNECTION'
export const FETCH_CAM_CONNECTION = 'FETCH_CAM_CONNECTION'
export const GET_CAM_CONNECTION_SUCCESS = 'GET_CAM_CONNECTION_SUCCESS'
export const FETCH_CAM_CONNECTION_SUCCESS = 'FETCH_CAM_CONNECTION_SUCCESS'
export const GET_CAM_CONNECTION_FAILURE = 'GET_CAM_CONNECTION_FAILURE'
export const FETCH_CAM_CONNECTION_FAILURE = 'FETCH_CAM_CONNECTION_FAILURE'
export const EDIT_CAM_CONNECTION = 'EDIT_CAM_CONNECTION'
export const EDIT_CAM_CONNECTION_SUCCESS = 'EDIT_CAM_CONNECTION_SUCCESS'
export const EDIT_CAM_CONNECTION_FAILURE = 'EDIT_CAM_CONNECTION_FAILURE'

//change cam params
export const GET_CAM_PARAMS = 'GET_CAM_PARAMS'
export const FETCH_CAM_PARAMS = 'FETCH_CAM_PARAMS'
export const GET_CAM_PARAMS_SUCCESS = 'GET_CAM_PARAMS_SUCCESS'
export const FETCH_CAM_PARAMS_SUCCESS = 'FETCH_CAM_PARAMS_SUCCESS'
export const GET_CAM_PARAMS_FAILURE = 'GET_CAM_PARAMS_FAILURE'
export const FETCH_CAM_PARAMS_FAILURE = 'FETCH_CAM_PARAMS_FAILURE'
export const EDIT_CAM_PARAMS = 'EDIT_CAM_PARAMS'
export const EDIT_CAM_PARAMS_SUCCESS = 'EDIT_CAM_PARAMS_SUCCESS'
export const EDIT_CAM_PARAMS_FAILURE = 'EDIT_CAM_PARAMS_FAILURE'

// change cam functions
export const FETCH_CAM_FUNCTIONS = 'FETCH_CAM_FUNCTIONS'
export const FETCH_CAM_FUNCTIONS_SUCCESS = 'FETCH_CAM_FUNCTIONS_SUCCESS'
export const FETCH_CAM_FUNCTIONS_FAILURE = 'FETCH_CAM_FUNCTIONS_FAILURE'
export const EDIT_CAM_FUNCTIONS = 'EDIT_CAM_FUNCTIONS'
export const EDIT_CAM_FUNCTIONS_SUCCESS = 'EDIT_CAM_FUNCTION_SUCCESS'
export const EDIT_CAM_FUNCTIONS_FAILURE = 'EDIT_CAM_FUNCTION_FAILURE'

export const GET_CAMERA_LOCATIONS = 'GET_CAMERA_LOCATIONS'
export const GET_CAMERA_LOCATIONS_SUCCESS = 'GET_CAMERA_LOCATIONS_SUCCESS'
export const GET_CAMERA_LOCATIONS_FAILURE = 'GET_CAMERA_LOCATIONS_FAILURE'
export const EDIT_CAMERA_LOCATIONS = 'EDIT_CAMERA_LOCATIONS'
export const EDIT_CAMERA_LOCATIONS_SUCCESS = 'EDIT_CAMERA_LOCATIONS_SUCCESS'
export const EDIT_CAMERA_LOCATIONS_FAILURE = 'EDIT_CAMERA_LOCATIONS_FAILURE'

export const GET_CAMERA_CONFIGS = 'GET_CAMERA_CONFIGS'
export const GET_CAMERA_CONFIGS_SUCCESS = 'GET_CAMERA_CONFIGS_SUCCESS'
export const GET_CAMERA_CONFIGS_FAILURE = 'GET_CAMERA_CONFIGS_FAILURE'
export const EDIT_CAMERA_CONFIGS = 'EDIT_CAMERA_CONFIGS'
export const EDIT_CAMERA_CONFIGS_SUCCESS = 'EDIT_CAMERA_CONFIGS_SUCCESS'
export const EDIT_CAMERA_CONFIGS_FAILURE = 'EDIT_CAMERA_CONFIGS_FAILURE'

export const CHECK_CAMERA_AUTH = 'CHECK_CAMERA_AUTH'
export const CHECK_CAMERA_AUTH_SUCCESS = 'CHECK_CAMERA_AUTH_SUCCESS'
export const CHECK_CAMERA_AUTH_FAILURE = 'CHECK_CAMERA_AUTH_FAILURE'

export const CHECK_CAMERA_IDENTITY = 'CHECK_CAMERA_IDENTITY'
export const CHECK_CAMERA_IDENTITY_SUCCESS = 'CHECK_CAMERA_IDENTITY_SUCCESS'
export const CHECK_CAMERA_IDENTITY_FAILURE = 'CHECK_CAMERA_IDENTITY_FAILURE'

export const CHECK_CAMERA_LOCATION = 'CHECK_CAMERA_LOCATION'
export const CHECK_CAMERA_LOCATION_SUCCESS = 'CHECK_CAMERA_LOCATION_SUCCESS'
export const CHECK_CAMERA_LOCATION_FAILURE = 'CHECK_CAMERA_LOCATION_FAILURE'

export const CHECK_CAMERA_CONFIGS = 'CHECK_CONFIGS'
export const CHECK_CAMERA_CONFIGS_SUCCESS = 'CHECK_CAMERA_CONFIGS_SUCCESS'
export const CHECK_CAMERA_CONFIGS_FAILURE = 'CHECK_CAMERA_CONFIGS_FAILURE'

export const FETCH_CAMERA_GROUP = 'FETCH_CAMERA_GROUP'
export const FETCH_CAMERA_GROUP_SUCCESS = 'FETCH_CAMERA_GROUP_SUCCESS'
export const FETCH_CAMERA_GROUP_FAILURE = 'FETCH_CAMERA_GROUP_FAILURE'

// export const GET_CAMERA_LOCATION_SUCCESS = 'GET_CAMERA_LOCATION_SUCCESS'

export const GET_CAMERA_POSITION_SUCCESS = 'GET_CAMERA_POSITION_SUCCESS'
export const NEXT_STEP = 'NEXT_STEP'
export const BACK_STEP = 'BACK_STEP'

// action fetch camera record videos
export const FETCH_CAM_RECORD_VIDEOS = 'FETCH_CAM_RECORD_VIDEOS'
export const FETCH_CAM_RECORD_VIDEOS_SUCCESS = 'FETCH_CAM_RECORD_VIDEOS_SUCCESS'
export const FETCH_CAM_RECORD_VIDEOS_FAILURE = 'FETCH_CAM_RECORD_VIDEOS_FAILURE'

export const UPDATE_SELECTED_RECORD_VIDEOS = 'UPDATE_SELECTED_RECORD_VIDEOS'

//action search camera
export const INIT_SEARCH_CAM = 'INIT_SEARCH_CAM'
export const GET_PROVINCES_AVAILABLE = 'GET_PROVINCES_AVAILABLE'
export const GET_PROVINCES_AVAILABLE_SUCCESS = 'GET_PROVINCES_AVAILABLE_SUCCESS'
export const GET_PROVINCES_AVAILABLE_FAILURE = 'GET_PROVINCES_AVAILABLE_FAILURE'
export const GET_DISTRICTS_AVAILABLE = 'GET_DISTRICTS_AVAILABLE'
export const GET_DISTRICTS_AVAILABLE_SUCCESS = 'GET_DISTRICTS_AVAILABLE_SUCCESS'
export const GET_DISTRICTS_AVAILABLE_FAILURE = 'GET_DISTRICTS_AVAILABLE_FAILURE'

export const SEARCH_CAMERA = 'SEARCH_CAMERA'
export const SEARCH_CAMERA_SUCCESS = 'SEARCH_CAMERA_SUCCESS'
export const SEARCH_CAMERA_FAILURE = 'SEARCH_CAMERA_FAILURE'

export const CHANGE_SEARCH_CAM_PARAMS = 'CHANGE_SEARCH_CAM_PARAMS'

//action for modal
export const TOGGLE_DELETE_MODAL = 'TOGGLE_DELETE_MODAL'
export const TOGGLE_ADD_MODAL = 'TOGGLE_ADD_MODAL'
export const SHOW_ADD_MODAL = 'SHOW_ADD_MODAL'
export const SHOW_EDIT_MODAL = 'SHOW_EDIT_MODAL'
export const CLOSE_ADD_MODAL = 'CLOSE_ADD_MODAL'
export const SHOW_DELETE_MODAL = 'SHOW_DELETE_MODAL'
export const CLOSE_DELETE_MODAL = 'CLOSE_DELETE_MODAL'
export const LOAD_MODAL_DATA_SUCCESS = 'LOAD_MODAL_DATA_SUCCESS'
export const SHOW_MODAL = 'SHOW_MODAL'
export const SHOW_GET_LOCATION_MODAL = 'SHOW_GET_LOCATION_MODAL'

export const SHOW_LOADING_MODAL = 'SHOW_LOADING_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'

export const SHOW_DELETE_CAM_MODAL = 'SHOW_DELETE_CAM_MODAL'
export const SHOW_DELETE_VEHICLE_MODAL = 'SHOW_DELETE_VEHICLE_MODAL'
export const MODAL__SHOW_ADD_CAM = 'MODAL__SHOW_ADD_CAM'

export const MODAL__SHOW_ADD_TO_BLACK_LIST = 'MODAL__SHOW_ADD_TO_BLACK_LIST'
export const MODAL__SHOW_EDIT_VEHICLE_FROM_BLACK_LIST = 'MODAL__SHOW_EDIT_VEHICLE_FROM_BLACK_LIST'
export const MODAL__SHOW_CAM_INFO = 'MODAL__SHOW_CAM_INFO'
export const MODAL__SHOW_EXPORT_PDF = 'MODAL__SHOW_EXPORT_PDF'

//action for ui
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION'
export const DISMISS_NOTIFICATION = 'DISMISS_NOTIFICATION'
export const TOGGLE_CAMERA_FILTER = 'TOGGLE_CAMERA_FILTER'
export const TOGGLE_SETTINGS_MENU = 'TOGGLE_SETTINGS_MENU'
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER'
export const TOGGLE_VIOLATIONS_FILTER = 'TOGGLE_VIOLATIONS_FILTER'

//action for util
export const LOAD_DISTRICT = 'LOAD_DISTRICT'
export const LOAD_DISTRICT_SUCCESS = 'LOAD_DISTRICT_SUCCESS'
export const LOAD_DISTRICT_FAILURE = 'LOAD_DISTRICT_FAILURE'

export const LOAD_COMMUNE = 'LOAD_COMMUNE'
export const LOAD_COMMUNE_SUCCESS = 'LOAD_COMMUNE_SUCCESS'
export const LOAD_COMMUNE_FAILURE = 'LOAD_COMMUNE_FAILURE'

export const SHOW_INFO_WINDOW = 'SHOW_INFO_WINDOW'
export const CLOSE_INFO_WINDOW = 'CLOSE_INFO_WINDOW'

//action for follow list
export const START_FOLLOWLIST = 'START_FOLLOWLIST'
export const GET_FOLLOWLIST = 'GET_FOLLOWLIST'
export const GET_FOLLOWLIST_SUCCESS = 'GET_FOLLOWLIST_SUCCESS'
export const GOTO_FOLLOWLIST_PAGE = 'GOTO_FOLLOWLIST_PAGE'
export const EXIT_FOLLOWLIST_PAGE = 'EXIT_FOLLOWLIST_PAGE'

export const CHANGE_LIST_SIZE = 'CHANGE_LIST_SIZE'

export const CHANGE_FOLLOWLIST_PAGE = 'CHANGE_FOLLOWLIST_PAGE'

export const ADD_CAM_TO_FOLLOWLIST = 'ADD_CAM_TO_FOLLOWLIST'
export const ADD_CAM_TO_FOLLOWLIST_SUCCESS = 'ADD_CAM_TO_FOLLOWLIST_SUCCESS'
export const ADD_CAM_TO_FOLLOWLIST_FAILURE = 'ADD_CAM_TO_FOLLOWLIST_FAILURE'

export const REMOVE_CAM_FROM_FOLLOWLIST = 'REMOVE_CAM_FROM_FOLLOWLIST'
export const REMOVE_CAM_FROM_FOLLOWLIST_SUCCESS = 'REMOVE_CAM_FROM_FOLLOWLIST_SUCCESS'
export const REMOVE_CAM_FROM_FOLLOWLIST_FAILURE = 'REMOVE_CAM_FROM_FOLLOWLIST_FAILURE'

//action for snackbar
export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR'
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR'

// action for political
export const GET_ALL_PROVINCES = 'GET_ALL_PROVINCES'
export const GET_PROVINCES = 'GET_PROVINCES'
export const GET_PROVINCES_SUCCESS = 'GET_PROVINCES_SUCCESS'
export const GET_DISTRICTS = 'GET_DISTRICTS'
export const FETCH_DISTRICTS = 'FETCH_DISTRICTS'
export const GET_DISTRICTS_SUCCESS = 'GET_DISTRICTS_SUCCESS'
export const GET_COMMUNES = 'GET_COMMUNES'
export const FETCH_COMMUNES = 'FETCH_COMMUNES'
export const GET_COMMUNES_SUCCESS = 'GET_COMMUNES_SUCCESS'
export const GET_POLITICAL_SUCCESS = 'GET_POLITICAL_SUCCESS'


export const CLEAR_PROVINCE = 'CLEAR_PROVINCE'
export const CLEAR_DISTRICT = 'CLEAR_DISTRICT'
export const RELOAD_POLITICAL = 'RELOAD_POLITICAL'

//action for group
export const CREATE_GROUP = 'CREATE_GROUP'
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS'
export const CREATE_GROUP_FAILURE = 'CREATE_GROUP_FAILURE'

export const GET_DATA_BEFORE_CONNECT = 'GET_DATA_BEFORE_CONNECT'

//action for map
export const FOCUS_ON_CAM = 'FOCUS_ON_CAM'
export const FOCUS_FIRST_CAM = 'FOCUS_FIRST_CAM'
export const CHANGE_BOUNDS_MAP = 'CHANGE_BOUNDS_MAP'
export const CANCEL_FOCUSED_CAM = 'CANCEL_FOCUSED_CAM'
export const TOGGLE_ADD_CAM_MAP = 'TOGGLE_ADD_CAM_MAP'
export const TOGGLE_EDIT_CAM_MAP = 'TOGGLE_EDIT_CAM_MAP'

//action for manage cam
export const SWITCH_TAB = 'SWITCH_TAB'

//action for search vehicles
export const CLEAR_VEHCLIES = 'CLEAR_VEHICLES'
export const SEARCH_VEHICLES = 'SEARCH_VEHICLES'
export const SEARCH_VEHICLES_SUCCESS = 'SEARCH_VEHICLES_SUCCESS'
export const SEARCH_VEHICLES_FAILURE = 'SEARCH_VEHICLES_FAILURE'
export const HOVER_ROW_VEHICLE = 'HOVER_ROW_VEHICLE'
export const CANCEL_HOVER_ROW_VEHICLE = 'CANCEL_HOVER_ROW_VEHICLE'
export const FOCUS_VEHICLE = 'FOCUS_VEHICLE'

// toggle active cam
export const CHANGE_CAM_STATUS = 'CHANGE_CAM_STATUS'
export const CHANGE_CAM_STATUS_SUCCESS = 'CHANGE_CAM_STATUS_SUCCESS'
export const CHANGE_CAM_STATUS_FAILURE = 'CHANGE_CAM_STATUS_FAILURE'

export const CLEAR_CAM_STATE = 'CLEAR_CAM_STATE'
export const CANCEL_WEBSOCKET = 'CANCEL_WEBSOCKET'

export const FETCH_CAMS_NOT_FOLLOWED = 'FETCH_CAMS_NOT_FOLLOWED'
export const FETCH_CAMS_NOT_FOLLOWED_SUCCESS = 'FETCH_CAMS_NOT_FOLLOWED_SUCCESS'
export const FETCH_CAMS_NOT_FOLLOWED_FAILURE = 'FETCH_CAMS_NOT_FOLLOWED_FAILURE'

export const CHANGE_SEARCH_STRING = 'CHANGE_SEARCH_STRING'

export const UPDATE_FOLLOWLIST = 'UPDATE_FOLLOWLIST'
export const START_CAM_STREAM_SUCCESS = 'START_CAM_STREAM_SUCCESS'
export const ADD_CAM_STREAM = 'ADD_CAM_STREAM'
export const ADD_CAM_STREAM_SUCCESS = 'ADD_CAM_STREAM_SUCCESS'

export const REMOVE_CAM_STREAM_SUCCESS = 'REMOVE_CAM_STREAM_SUCCESS'

export const FETCH_FOLLOW_LIST = 'FETCH_FOLLOW_LIST'
export const FETCH_FOLLOW_LIST_SUCCESS = 'FETCH_FOLLOW_LIST_SUCCESS'
export const FETCH_FOLLOW_LIST_FAILURE = 'FETCH_FOLLOW_LIST_FAILURE'

export const FETCH_STREAMING_CAM = 'FETCH_STREAMING_CAM'
export const FETCH_STREAMING_CAM_SUCCESS = 'FETCH_STREAMING_CAM_SUCCESS'
export const FETCH_STREAMING_CAM_FAILURE = 'FETCH_STREAMING_CAM_FAILURE'

// black list
export const BLACK_LIST__FETCH_LIST = 'BLACK_LIST__FETCH_LIST'
export const BLACK_LIST__FETCH_LIST_SUCCESS = 'BLACK_LIST__FETCH_LIST_SUCCESS'
export const BLACK_LIST__FETCH_LIST_FAILURE = 'BLACK_LIST__FETCH_LIST_FAILURE'

export const BLACK_LIST__ADD_VEHICLE = 'BLACK_LIST__ADD_VEHICLE'
export const BLACK_LIST__ADD_VEHICLE_SUCCESS = 'BLACK_LIST__ADD_VEHICLE_SUCCESS'
export const BLACK_LIST__ADD_VEHICLE_FAILURE = 'BLACK_LIST__ADD_VEHICLE_FAILURE'

export const BLACK_LIST__GET_CURRENT_VEHICLE_ID = 'BLACK_LIST__GET_CURRENT_VEHICLE_ID'

export const BLACK_LIST__FETCH_VEHICLE_DATA = 'BLACK_LIST__FETCH_VEHICLE_DATA'
export const BLACK_LIST__FETCH_VEHICLE_DATA_SUCCESS = 'BLACK_LIST__FETCH_VEHICLE_DATA_SUCCESS'
export const BLACK_LIST__FETCH_VEHICLE_DATA_FAILURE = 'BLACK_LIST__FETCH_VEHICLE_DATA_FAILURE'

export const BLACK_LIST__EDIT_VEHICLE_DATA = 'BLACK_LIST__EDIT_VEHICLE_DATA'
export const BLACK_LIST__EDIT_VEHICLE_DATA_SUCCESS = 'BLACK_LIST__EDIT_VEHICLE_DATA_SUCCESS'
export const BLACK_LIST__EDIT_VEHICLE_DATA_FAILURE = 'BLACK_LIST__EDIT_VEHICLE_DATA_FAILURE'

export const BLACK_LIST__DELETE_VEHICLE = 'BLACK_LIST__DELETE_VEHICLE'
export const BLACK_LIST__DELETE_VEHICLE_SUCCESS = 'BLACK_LIST__DELETE_VEHICLE_SUCCESS'
export const BLACK_LIST__DELETE_VEHICLE_FAILURE = 'BLACK_LIST__DELETE_VEHICLE_FAILURE'

export const BLACK_LIST__FETCH_VEHICLE_HISTORY = 'BLACK_LIST__FETCH_VEHICLE_HISTORY'
export const BLACK_LIST__FETCH_VEHICLE_HISTORY_SUCCESS = 'BLACK_LIST__FETCH_VEHICLE_HISTORY_SUCCESS'
export const BLACK_LIST__FETCH_VEHICLE_HISTORY_FAILURE = 'BLACK_LIST__FETCH_VEHICLE_HISTORY_FAILURE'

export const BLACK_LIST__FOCUS_VEHICLE_HISTORY = 'BLACK_LIST__FOCUS_VEHICLE_HISTORY'
export const BLACK_LIST__CANCEL_FOCUS_VEHICLE_HISTORY = 'BLACK_LIST__CANCEL_FOCUS_VEHICLE_HISTORY'

// notification
export const NOTIFICATION__FETCH = 'NOTIFICATION__FETCH'
export const NOTIFICATION__FETCH_SUCCESS = 'NOTIFICATION__FETCH_SUCCESS'
export const NOTIFICATION__FETCH_FAILURE = 'NOTIFICATION__FETCH_FAILURE'

export const NOTIFICATION__CONNECT = 'NOTIFICATION__CONNECT'
export const NOTIFICATION__PUSH = 'NOTIFICATION__PUSH'

export const NOTIFICATION__READ_MESSAGE = 'NOTIFICATION__READ_MESSAGE'
export const NOTIFICATION__READ_MESSAGE_SUCCESS = 'NOTIFICATION__READ_MESSAGE_SUCCESS'

export const NOTIFICATION__UNREAD_COUNT = 'NOTIFICATION__UNREAD_COUNT'
export const NOTIFICATION__UNREAD_COUNT_SUCCESS = 'NOTIFICATION__UNREAD_COUNT_SUCCESS'
export const NOTIFICATION__UNREAD_COUNT_FAILURE = 'NOTIFICATION__UNREAD_COUNT_FAILURE'

// violations
export const FETCH_VIOLATIONS = 'FETCH_VIOALTIONS'
export const FETCH_VIOLATIONS_SUCCESS = 'FETCH_VIOLATIONS_SUCCESS'
export const FETCH_VIOLATIONS_FAILURE = 'FETCH_VIOALTIONS_FAILURE'

export const FETCH_VIOLATION_DETAIL = 'FETCH_VIOLATION_DETAIL'
export const FETCH_VIOLATION_DETAIL_SUCCESS = 'FETCH_VIOLATION_DETAIL_SUCCESS'
export const FETCH_VIOLATION_DETAIL_FAILURE = 'FETCH_VIOLATION_DETAIL_FAILURE'

export const EDIT_VIOLATION_DETAIL = 'EDIT_VIOLATION_DETAIL'
export const EDIT_VIOLATION_DETAIL_SUCCESS = 'EDIT_VIOLATION_DETAIL_SUCCESS'
export const EDIT_VIOLATION_DETAIL_FAILURE = 'EDIT_VIOLATION_DETAIL_FAILURE'

export const CHANGE_VIOLATION_PARAM = 'CHANGE_VIOLATION_PARAM'

export const UPDATE_SELECTED_VIOLATIONS = 'UPDATE_SELECTED_VIOLATIONS'

export const CHANGE_PARAM_VIOLATION_FILTER = 'CHANGE_PARAM_VIOLATION_FILTER'
export const FILTER_VIOLATIONS = 'FILTER_VIOALTIONS'
export const FILTER_VIOLATIONS_SUCCESS = 'FILTER_VIOALTIONS_SUCCESS'
export const FILTER_VIOLATIONS_FAILURE = 'FILTER_VIOALTIONS_FAILURE'

export const DELETE_VIOLATIONS = 'DELETE_VIOLATIONS'
export const DELETE_VIOLATIONS_SUCCESS = 'DELETE_VIOLATIONS_SUCCESS'
export const DELETE_VIOLATIONS_FAILURE = 'DELETE_VIOLATIONS_FAILURE'

export const DELETE_SINGLE_VIOLATION = 'DELETE_SINGLE_VIOLATION'
export const DELETE_SINGLE_VIOLATION_SUCCESS = 'DELETE_SINGLE_VIOLATION_SUCCESS'
export const DELETE_SINGLE_VIOLATION_FAILURE = 'DELETE_SINGLE_VIOLATION_FAILURE'

export const APPROVE_VIOLATIONS = 'APPROVE_VIOLATIONS'
export const APPROVE_VIOLATIONS_SUCCESS = 'APPROVE_VIOLATIONS_SUCCESS'
export const APPROVE_VIOLATIONS_FAILURE = 'APPROVE_VIOLATIONS_FAILURE'

export const UNAPPROVE_VIOLATIONS = 'UNAPPROVE_VIOLATIONS'
export const UNAPPROVE_VIOLATIONS_SUCCESS = 'UNAPPROVE_VIOLATIONS_SUCCESS'
export const UNAPPROVE_VIOLATIONS_FAILURE = 'UNAPPROVE_VIOLATIONS_FAILURE'

export const EXPORT_VIOLATION_PDF = 'EXPORT_VIOLATION_PDF'
export const EXPORT_VIOLATION_PDF_SUCCESS = 'EXPORT_VIOLATION_PDF_SUCCESS'
export const EXPORT_VIOLATION_PDF_FAILURE = 'EXPORT_VIOLATION_PDF_FAILURE'

// record video
export const FILTER_RECORD_VIDEOS = 'FILTER_RECORD_VIDEOS'
export const FILTER_RECORD_VIDEOS_SUCCESS = 'FILTER_RECORD_VIDEOS_SUCCESS'
export const FILTER_RECORD_VIDEOS_FAILURE = 'FILTER_RECORD_VIDEOS_FAILURE'

export const DELETE_RECORD_VIDEOS = 'DELETE_RECORD_VIDEOS'
export const DELETE_RECORD_VIDEOS_SUCCESS = 'DELETE_RECORD_VIDEOS_SUCCESS'
export const DELETE_RECORD_VIDEOS_FAILURE = 'DELETE_RECORD_VIDEOS_FAILURE'

export const UPDATE_SELECTED_VIDEOS = 'UPDATE_SELECTED_VIDEOS'

export const DISPLAY_VIDEO = 'DISPLAY_VIDEO'

// flow
export const FETCH_FLOW_CAMERAS = 'FETCH_FLOW_CAMERAS'
export const FETCH_FLOW_CAMERAS_SUCCESS = 'FETCH_FLOW_CAMERAS_SUCCESS'
export const FETCH_FLOW_CAMERAS_FAILURE = 'FETCH_FLOW_CAMERAS_FAILURE'

export const FETCH_FLOW_CHART_DATA = 'FETCH_FLOW_CHART_DATA'
export const FETCH_FLOW_CHART_DATA_SUCCESS = 'FETCH_FLOW_CHART_DATA_SUCCESS'
export const FETCH_FLOW_CHART_DATA_FAILURE = 'FETCH_FLOW_CHART_DATA_FAILURE'

export const CHANGE_VEHICLE_TYPE = 'CHANGE_VEHICLE_TYPE'

export const CHANGE_CHART_PARAMS = 'CHANGE_CHART_PARAMS'

// traffic light
export const FETCH_CONFIG_TRAFFIC_LIGHT = 'FETCH_CONFIG_TRAFFIC_LIGHT'
export const FETCH_CONFIG_TRAFFIC_LIGHT_SUCCESS = 'FETCH_CONFIG_TRAFFIC_LIGHT_SUCCESS'
export const FETCH_CONFIG_TRAFFIC_LIGHT_FAILURE = 'FETCH_CONFIG_TRAFFIC_LIGHT_FAILURE'
export const EDIT_CONFIG_TRAFFIC_LIGHT = 'EDIT_CONFIG_TRAFFIC_LIGHT'
export const EDIT_CONFIG_TRAFFIC_LIGHT_SUCCESS = 'EDIT_CONFIG_TRAFFIC_LIGHT_SUCCESS'
export const EDIT_CONFIG_TRAFFIC_LIGHT_FAILURE = 'EDIT_CONFIG_TRAFFIC_LIGHT_FAILURE'

export const FETCH_CONFIG_TRAFFIC_LIGHT_VIA_MODE = 'FETCH_CONFIG_TRAFFIC_LIGHT_VIA_MODE'
export const FETCH_CONFIG_TRAFFIC_LIGHT_VIA_MODE_SUCCESS =
  'FETCH_CONFIG_TRAFFIC_LIGHT_VIA_MODE_SUCCESS'
export const FETCH_CONFIG_TRAFFIC_LIGHT_VIA_MODE_FAILURE =
  'FETCH_CONFIG_TRAFFIC_LIGHT_VIA_MODE_FAILURE'

export const FETCH_INTELLIGENT_CONFIG_VIA_TYPE = 'FETCH_INTELLIGENT_CONFIG_VIA_TYPE'
export const FETCH_INTELLIGENT_CONFIG_VIA_TYPE_SUCCESS = 'FETCH_INTELLIGENT_CONFIG_VIA_TYPE_SUCCESS'
export const FETCH_INTELLIGENT_CONFIG_VIA_TYPE_FAILRE = 'FETCH_INTELLIGENT_CONFIG_VIA_TYPE_FAILURE'

export const SWITH_TRAFFIC_LIGHT_MODE = 'SWITCH_TRAFFIC_LIGHT_MODE'

export const FILTER_LIGHT_PERIOD_CHART_DATA = 'FILTER_LIGHT_PERIOD_CHART_DATA'
export const FILTER_LIGHT_PERIOD_CHART_DATA_SUCCESS = 'FILTER_LIGHT_PERIOD_CHART_DATA_SUCCESS'
export const FILTER_LIGHT_PERIOD_CHART_DATA_FAILURE = 'FILTER_LIGHT_PERIOD_CHART_DATA_FAILURE'

export const FETCH_LIGHT_PERIOD_CHART_DATA = 'FETCH_LIGHT_PERIOD_CHART_DATA'
export const FETCH_LIGHT_PERIOD_CHART_DATA_SUCCESS = 'FETCH_LIGHT_PERIOD_CHART_DATA_SUCCESS'
export const FETCH_LIGHT_PERIOD_CHART_DATA_FAILURE = 'FETCH_LIGHT_PERIOD_CHART_DATA_FAILURE'