export const VideoTypes = {
  ABORT: 'ABORT',
  CAN_PLAY: 'CAN_PLAY',
  CAN_PLAY_THROUGH: 'CAN_PLAY_THROUGH',
  DURATION_CHANGE: 'DURATION_CHANGE',
  EMPTIED: 'EMPTIED',
  ENDED: 'ENDED',
  ERROR: 'ERROR',
  LOADED_DATA: 'LOADED_DATA',
  LOADED_META_DATA: 'LOADED_META_DATA',
  LOAD_START: 'LOAD_START',
  PAUSE: 'PAUSE',
  PLAY: 'PLAY',
  PLAYING: 'PLAYING',
  PROGRESS: 'PROGRESS',
  RATE_CHANGE: 'RATE_CHANGE',
  SEEKED: 'SEEKED',
  SEEKING: 'SEEKING',
  SEEKING_TIME: 'SEEKING_TIME',
  END_SEEKNG: 'END_SEEKNG',
  STALLED: 'STALLED',
  SUSPEND: 'SUSPEND',
  TIME_UPDATE: 'TIME_UPDATE',
  VOLUME_CHANGE: 'VOLUME_CHANGE',
  WAITING: 'WAITING',
}

export const PlayerTypes = {
  OPERATE: 'OPERATE',
  FULLSCREEN_CHANGE: 'FULLSCREEN_CHANGE',
  PLAYER_ACTIVATE: 'PLAYER_ACTIVATE',
  USER_ACTIVATE: 'USER_ACTIVATE',
  CONTROL_BAR_ACTIVATE: 'CONTROL_BAR_ACTIVATE'
}
